//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DHCPDConfig.g4 by ANTLR 4.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DHCPDConfigParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.1")]
[System.CLSCompliant(false)]
public interface IDHCPDConfigListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.rangeLow6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangeLow6([NotNull] DHCPDConfigParser.RangeLow6Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.rangeLow6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangeLow6([NotNull] DHCPDConfigParser.RangeLow6Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.netmask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNetmask([NotNull] DHCPDConfigParser.NetmaskContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.netmask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNetmask([NotNull] DHCPDConfigParser.NetmaskContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.subnet6Declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubnet6Declaration([NotNull] DHCPDConfigParser.Subnet6DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.subnet6Declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubnet6Declaration([NotNull] DHCPDConfigParser.Subnet6DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.sharedNetwork"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSharedNetwork([NotNull] DHCPDConfigParser.SharedNetworkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.sharedNetwork"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSharedNetwork([NotNull] DHCPDConfigParser.SharedNetworkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.config"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConfig([NotNull] DHCPDConfigParser.ConfigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.config"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConfig([NotNull] DHCPDConfigParser.ConfigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.rangeHigh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangeHigh([NotNull] DHCPDConfigParser.RangeHighContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.rangeHigh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangeHigh([NotNull] DHCPDConfigParser.RangeHighContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] DHCPDConfigParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] DHCPDConfigParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.fixedPrefix6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFixedPrefix6([NotNull] DHCPDConfigParser.FixedPrefix6Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.fixedPrefix6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFixedPrefix6([NotNull] DHCPDConfigParser.FixedPrefix6Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.hostname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHostname([NotNull] DHCPDConfigParser.HostnameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.hostname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHostname([NotNull] DHCPDConfigParser.HostnameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.addressRangeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddressRangeDeclaration([NotNull] DHCPDConfigParser.AddressRangeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.addressRangeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddressRangeDeclaration([NotNull] DHCPDConfigParser.AddressRangeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.addressRange6Declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddressRange6Declaration([NotNull] DHCPDConfigParser.AddressRange6DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.addressRange6Declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddressRange6Declaration([NotNull] DHCPDConfigParser.AddressRange6DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.leaseAddress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeaseAddress([NotNull] DHCPDConfigParser.LeaseAddressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.leaseAddress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeaseAddress([NotNull] DHCPDConfigParser.LeaseAddressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.rangeLow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangeLow([NotNull] DHCPDConfigParser.RangeLowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.rangeLow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangeLow([NotNull] DHCPDConfigParser.RangeLowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.ip4Address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIp4Address([NotNull] DHCPDConfigParser.Ip4AddressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.ip4Address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIp4Address([NotNull] DHCPDConfigParser.Ip4AddressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] DHCPDConfigParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] DHCPDConfigParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.lease"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLease([NotNull] DHCPDConfigParser.LeaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.lease"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLease([NotNull] DHCPDConfigParser.LeaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.optionOptionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionOptionStatement([NotNull] DHCPDConfigParser.OptionOptionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.optionOptionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionOptionStatement([NotNull] DHCPDConfigParser.OptionOptionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.optionParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionParam([NotNull] DHCPDConfigParser.OptionParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.optionParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionParam([NotNull] DHCPDConfigParser.OptionParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.ipAddressWithSubnet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIpAddressWithSubnet([NotNull] DHCPDConfigParser.IpAddressWithSubnetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.ipAddressWithSubnet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIpAddressWithSubnet([NotNull] DHCPDConfigParser.IpAddressWithSubnetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.fixedAddress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFixedAddress([NotNull] DHCPDConfigParser.FixedAddressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.fixedAddress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFixedAddress([NotNull] DHCPDConfigParser.FixedAddressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.leaseParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeaseParameters([NotNull] DHCPDConfigParser.LeaseParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.leaseParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeaseParameters([NotNull] DHCPDConfigParser.LeaseParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.sharedNetworkDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSharedNetworkDeclaration([NotNull] DHCPDConfigParser.SharedNetworkDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.sharedNetworkDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSharedNetworkDeclaration([NotNull] DHCPDConfigParser.SharedNetworkDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.optionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionStatement([NotNull] DHCPDConfigParser.OptionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.optionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionStatement([NotNull] DHCPDConfigParser.OptionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.subnetDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubnetDeclaration([NotNull] DHCPDConfigParser.SubnetDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.subnetDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubnetDeclaration([NotNull] DHCPDConfigParser.SubnetDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.leaseTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeaseTime([NotNull] DHCPDConfigParser.LeaseTimeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.leaseTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeaseTime([NotNull] DHCPDConfigParser.LeaseTimeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.failoverDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFailoverDeclaration([NotNull] DHCPDConfigParser.FailoverDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.failoverDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFailoverDeclaration([NotNull] DHCPDConfigParser.FailoverDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.klass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKlass([NotNull] DHCPDConfigParser.KlassContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.klass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKlass([NotNull] DHCPDConfigParser.KlassContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.state"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterState([NotNull] DHCPDConfigParser.StateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.state"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitState([NotNull] DHCPDConfigParser.StateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.groupDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupDeclaration([NotNull] DHCPDConfigParser.GroupDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.groupDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupDeclaration([NotNull] DHCPDConfigParser.GroupDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDate([NotNull] DHCPDConfigParser.DateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDate([NotNull] DHCPDConfigParser.DateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.timestamp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTimestamp([NotNull] DHCPDConfigParser.TimestampContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.timestamp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTimestamp([NotNull] DHCPDConfigParser.TimestampContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.hostDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHostDeclaration([NotNull] DHCPDConfigParser.HostDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.hostDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHostDeclaration([NotNull] DHCPDConfigParser.HostDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.subnet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubnet([NotNull] DHCPDConfigParser.SubnetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.subnet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubnet([NotNull] DHCPDConfigParser.SubnetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] DHCPDConfigParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] DHCPDConfigParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.leaseDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeaseDeclaration([NotNull] DHCPDConfigParser.LeaseDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.leaseDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeaseDeclaration([NotNull] DHCPDConfigParser.LeaseDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.failoverStateStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFailoverStateStatement([NotNull] DHCPDConfigParser.FailoverStateStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.failoverStateStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFailoverStateStatement([NotNull] DHCPDConfigParser.FailoverStateStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatements([NotNull] DHCPDConfigParser.StatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatements([NotNull] DHCPDConfigParser.StatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.fixedAddressParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFixedAddressParameter([NotNull] DHCPDConfigParser.FixedAddressParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.fixedAddressParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFixedAddressParameter([NotNull] DHCPDConfigParser.FixedAddressParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.subnet6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubnet6([NotNull] DHCPDConfigParser.Subnet6Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.subnet6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubnet6([NotNull] DHCPDConfigParser.Subnet6Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.hostnameOrIpAddress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHostnameOrIpAddress([NotNull] DHCPDConfigParser.HostnameOrIpAddressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.hostnameOrIpAddress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHostnameOrIpAddress([NotNull] DHCPDConfigParser.HostnameOrIpAddressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.ip6net"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIp6net([NotNull] DHCPDConfigParser.Ip6netContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.ip6net"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIp6net([NotNull] DHCPDConfigParser.Ip6netContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.ip6Address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIp6Address([NotNull] DHCPDConfigParser.Ip6AddressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.ip6Address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIp6Address([NotNull] DHCPDConfigParser.Ip6AddressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.hardwareParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHardwareParameter([NotNull] DHCPDConfigParser.HardwareParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.hardwareParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHardwareParameter([NotNull] DHCPDConfigParser.HardwareParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.stringParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringParameter([NotNull] DHCPDConfigParser.StringParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.stringParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringParameter([NotNull] DHCPDConfigParser.StringParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDeclaration([NotNull] DHCPDConfigParser.ClassDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDeclaration([NotNull] DHCPDConfigParser.ClassDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.rangeHigh6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangeHigh6([NotNull] DHCPDConfigParser.RangeHigh6Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.rangeHigh6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangeHigh6([NotNull] DHCPDConfigParser.RangeHigh6Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.ipAddrOrHostnames"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIpAddrOrHostnames([NotNull] DHCPDConfigParser.IpAddrOrHostnamesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.ipAddrOrHostnames"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIpAddrOrHostnames([NotNull] DHCPDConfigParser.IpAddrOrHostnamesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.startEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStartEnd([NotNull] DHCPDConfigParser.StartEndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.startEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStartEnd([NotNull] DHCPDConfigParser.StartEndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.leaseParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeaseParameter([NotNull] DHCPDConfigParser.LeaseParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.leaseParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeaseParameter([NotNull] DHCPDConfigParser.LeaseParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.poolDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPoolDeclaration([NotNull] DHCPDConfigParser.PoolDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.poolDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPoolDeclaration([NotNull] DHCPDConfigParser.PoolDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.ip6Prefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIp6Prefix([NotNull] DHCPDConfigParser.Ip6PrefixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.ip6Prefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIp6Prefix([NotNull] DHCPDConfigParser.Ip6PrefixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.peerStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPeerStatement([NotNull] DHCPDConfigParser.PeerStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.peerStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPeerStatement([NotNull] DHCPDConfigParser.PeerStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.failoverStateDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFailoverStateDeclaration([NotNull] DHCPDConfigParser.FailoverStateDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.failoverStateDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFailoverStateDeclaration([NotNull] DHCPDConfigParser.FailoverStateDeclarationContext context);
}
