//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DHCPDConfig.g4 by ANTLR 4.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDHCPDConfigListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.1")]
[System.CLSCompliant(false)]
public partial class DHCPDConfigBaseListener : IDHCPDConfigListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.rangeLow6"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRangeLow6([NotNull] DHCPDConfigParser.RangeLow6Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.rangeLow6"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRangeLow6([NotNull] DHCPDConfigParser.RangeLow6Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.netmask"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNetmask([NotNull] DHCPDConfigParser.NetmaskContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.netmask"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNetmask([NotNull] DHCPDConfigParser.NetmaskContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.subnet6Declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubnet6Declaration([NotNull] DHCPDConfigParser.Subnet6DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.subnet6Declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubnet6Declaration([NotNull] DHCPDConfigParser.Subnet6DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.sharedNetwork"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSharedNetwork([NotNull] DHCPDConfigParser.SharedNetworkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.sharedNetwork"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSharedNetwork([NotNull] DHCPDConfigParser.SharedNetworkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.config"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConfig([NotNull] DHCPDConfigParser.ConfigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.config"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConfig([NotNull] DHCPDConfigParser.ConfigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.rangeHigh"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRangeHigh([NotNull] DHCPDConfigParser.RangeHighContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.rangeHigh"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRangeHigh([NotNull] DHCPDConfigParser.RangeHighContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] DHCPDConfigParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] DHCPDConfigParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.fixedPrefix6"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFixedPrefix6([NotNull] DHCPDConfigParser.FixedPrefix6Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.fixedPrefix6"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFixedPrefix6([NotNull] DHCPDConfigParser.FixedPrefix6Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.hostname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHostname([NotNull] DHCPDConfigParser.HostnameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.hostname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHostname([NotNull] DHCPDConfigParser.HostnameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.addressRangeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddressRangeDeclaration([NotNull] DHCPDConfigParser.AddressRangeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.addressRangeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddressRangeDeclaration([NotNull] DHCPDConfigParser.AddressRangeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.addressRange6Declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddressRange6Declaration([NotNull] DHCPDConfigParser.AddressRange6DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.addressRange6Declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddressRange6Declaration([NotNull] DHCPDConfigParser.AddressRange6DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.leaseAddress"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeaseAddress([NotNull] DHCPDConfigParser.LeaseAddressContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.leaseAddress"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeaseAddress([NotNull] DHCPDConfigParser.LeaseAddressContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.rangeLow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRangeLow([NotNull] DHCPDConfigParser.RangeLowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.rangeLow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRangeLow([NotNull] DHCPDConfigParser.RangeLowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.ip4Address"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIp4Address([NotNull] DHCPDConfigParser.Ip4AddressContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.ip4Address"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIp4Address([NotNull] DHCPDConfigParser.Ip4AddressContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] DHCPDConfigParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] DHCPDConfigParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.lease"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLease([NotNull] DHCPDConfigParser.LeaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.lease"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLease([NotNull] DHCPDConfigParser.LeaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.optionOptionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionOptionStatement([NotNull] DHCPDConfigParser.OptionOptionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.optionOptionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionOptionStatement([NotNull] DHCPDConfigParser.OptionOptionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.optionParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionParam([NotNull] DHCPDConfigParser.OptionParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.optionParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionParam([NotNull] DHCPDConfigParser.OptionParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.ipAddressWithSubnet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIpAddressWithSubnet([NotNull] DHCPDConfigParser.IpAddressWithSubnetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.ipAddressWithSubnet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIpAddressWithSubnet([NotNull] DHCPDConfigParser.IpAddressWithSubnetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.fixedAddress"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFixedAddress([NotNull] DHCPDConfigParser.FixedAddressContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.fixedAddress"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFixedAddress([NotNull] DHCPDConfigParser.FixedAddressContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.leaseParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeaseParameters([NotNull] DHCPDConfigParser.LeaseParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.leaseParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeaseParameters([NotNull] DHCPDConfigParser.LeaseParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.sharedNetworkDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSharedNetworkDeclaration([NotNull] DHCPDConfigParser.SharedNetworkDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.sharedNetworkDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSharedNetworkDeclaration([NotNull] DHCPDConfigParser.SharedNetworkDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.optionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionStatement([NotNull] DHCPDConfigParser.OptionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.optionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionStatement([NotNull] DHCPDConfigParser.OptionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.subnetDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubnetDeclaration([NotNull] DHCPDConfigParser.SubnetDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.subnetDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubnetDeclaration([NotNull] DHCPDConfigParser.SubnetDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.leaseTime"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeaseTime([NotNull] DHCPDConfigParser.LeaseTimeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.leaseTime"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeaseTime([NotNull] DHCPDConfigParser.LeaseTimeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.failoverDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFailoverDeclaration([NotNull] DHCPDConfigParser.FailoverDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.failoverDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFailoverDeclaration([NotNull] DHCPDConfigParser.FailoverDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.klass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKlass([NotNull] DHCPDConfigParser.KlassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.klass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKlass([NotNull] DHCPDConfigParser.KlassContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.state"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterState([NotNull] DHCPDConfigParser.StateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.state"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitState([NotNull] DHCPDConfigParser.StateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.groupDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupDeclaration([NotNull] DHCPDConfigParser.GroupDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.groupDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupDeclaration([NotNull] DHCPDConfigParser.GroupDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.date"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDate([NotNull] DHCPDConfigParser.DateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.date"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDate([NotNull] DHCPDConfigParser.DateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.timestamp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTimestamp([NotNull] DHCPDConfigParser.TimestampContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.timestamp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTimestamp([NotNull] DHCPDConfigParser.TimestampContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.hostDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHostDeclaration([NotNull] DHCPDConfigParser.HostDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.hostDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHostDeclaration([NotNull] DHCPDConfigParser.HostDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.subnet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubnet([NotNull] DHCPDConfigParser.SubnetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.subnet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubnet([NotNull] DHCPDConfigParser.SubnetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] DHCPDConfigParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] DHCPDConfigParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.leaseDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeaseDeclaration([NotNull] DHCPDConfigParser.LeaseDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.leaseDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeaseDeclaration([NotNull] DHCPDConfigParser.LeaseDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.failoverStateStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFailoverStateStatement([NotNull] DHCPDConfigParser.FailoverStateStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.failoverStateStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFailoverStateStatement([NotNull] DHCPDConfigParser.FailoverStateStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatements([NotNull] DHCPDConfigParser.StatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatements([NotNull] DHCPDConfigParser.StatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.fixedAddressParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFixedAddressParameter([NotNull] DHCPDConfigParser.FixedAddressParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.fixedAddressParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFixedAddressParameter([NotNull] DHCPDConfigParser.FixedAddressParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.subnet6"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubnet6([NotNull] DHCPDConfigParser.Subnet6Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.subnet6"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubnet6([NotNull] DHCPDConfigParser.Subnet6Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.hostnameOrIpAddress"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHostnameOrIpAddress([NotNull] DHCPDConfigParser.HostnameOrIpAddressContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.hostnameOrIpAddress"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHostnameOrIpAddress([NotNull] DHCPDConfigParser.HostnameOrIpAddressContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.ip6net"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIp6net([NotNull] DHCPDConfigParser.Ip6netContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.ip6net"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIp6net([NotNull] DHCPDConfigParser.Ip6netContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.ip6Address"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIp6Address([NotNull] DHCPDConfigParser.Ip6AddressContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.ip6Address"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIp6Address([NotNull] DHCPDConfigParser.Ip6AddressContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.hardwareParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHardwareParameter([NotNull] DHCPDConfigParser.HardwareParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.hardwareParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHardwareParameter([NotNull] DHCPDConfigParser.HardwareParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.stringParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringParameter([NotNull] DHCPDConfigParser.StringParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.stringParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringParameter([NotNull] DHCPDConfigParser.StringParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDeclaration([NotNull] DHCPDConfigParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDeclaration([NotNull] DHCPDConfigParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.rangeHigh6"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRangeHigh6([NotNull] DHCPDConfigParser.RangeHigh6Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.rangeHigh6"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRangeHigh6([NotNull] DHCPDConfigParser.RangeHigh6Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.ipAddrOrHostnames"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIpAddrOrHostnames([NotNull] DHCPDConfigParser.IpAddrOrHostnamesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.ipAddrOrHostnames"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIpAddrOrHostnames([NotNull] DHCPDConfigParser.IpAddrOrHostnamesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.startEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStartEnd([NotNull] DHCPDConfigParser.StartEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.startEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStartEnd([NotNull] DHCPDConfigParser.StartEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.leaseParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeaseParameter([NotNull] DHCPDConfigParser.LeaseParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.leaseParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeaseParameter([NotNull] DHCPDConfigParser.LeaseParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.poolDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPoolDeclaration([NotNull] DHCPDConfigParser.PoolDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.poolDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPoolDeclaration([NotNull] DHCPDConfigParser.PoolDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.ip6Prefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIp6Prefix([NotNull] DHCPDConfigParser.Ip6PrefixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.ip6Prefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIp6Prefix([NotNull] DHCPDConfigParser.Ip6PrefixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.peerStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPeerStatement([NotNull] DHCPDConfigParser.PeerStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.peerStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPeerStatement([NotNull] DHCPDConfigParser.PeerStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DHCPDConfigParser.failoverStateDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFailoverStateDeclaration([NotNull] DHCPDConfigParser.FailoverStateDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DHCPDConfigParser.failoverStateDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFailoverStateDeclaration([NotNull] DHCPDConfigParser.FailoverStateDeclarationContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
